root = "."
tmp_dir = "docker"

[build]
cmd = "go build -o ./docker/__debug_bin ."
bin = "./docker/__debug_bin"
full_bin = "APP_ENV=dev APP_USER=air /go/bin/dlv exec ./docker/__debug_bin --headless=true --listen=:2345 --api-version=2 --accept-multiclient"
include_ext = ["go", "tmpl"]
exclude_dir = ["./docker"]
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500 # ms

[log]
time = false

[misc]
clean_on_exit = false
