root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/__debug_bin ."
bin = "./tmp/__debug_bin"
full_bin = "APP_ENV=dev APP_USER=air /go/bin/dlv exec ./tmp/__debug_bin --headless=true --listen=:2345 --api-version=2 --accept-multiclient"
include_ext = ["go", "tpl"]
exclude_dir = ["./tmp"]
log = "air-debug.log"
delay = 5000 # ms
stop_on_error = false
send_interrupt = true
kill_delay = 1000 # ms

[log]
time = false

[misc]
clean_on_exit = true
