version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 2345:2345 # delve
    volumes:
      - .:/src
  app_test:
    build:
      context: .
    command: 'air -c .air-test.toml'
