version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 2345:2345
    volumes:
      - .:/go/src/github.com/usagiga/git-hooks
  app_test:
    build:
      context: .
    command: 'air -c .air-test.toml'
