name: "Go (Test / Vet / Build)"

on:
  push:
  pull_request:

jobs:
  build-test-lint:
    name: "Go (Test / Vet / Build)"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"
      - name: "vet"
        run: "make lint"
      - name: "test"
        run: "make test"
      - name: "build"
        run: "make build"
