name: "test"

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "1.19.2"
      - name: "vet"
        run: "make lint"
      - name: "build"
        run: "make build"
      - name: "test"
        run: "make test"
      - name: "notify if error"
        uses: actions/github-script@v4
        with:
          script: |-
            const isPR = context.eventName == 'pull_request';
            const jobUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            if (!isPR) {
              return;
            }
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Failed linte/build/test.\n${jobUrl}`
            });
        if: failure()
