name: "test"

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-go@v4"
        with:
          go-version: "1.21.5"
      - name: "vet"
        run: "make lint"
      - name: "test"
        run: "make test"
      - name: "build"
        run: "make build"
